### PR TITLE
Changed es6 to rip because of the need to rename files.

### PR DESCRIPTION
**Pull request by tkon99**

### CODE REVIEW

**Comment by grigio** [comment]
what's wrong with .es6\* ?

**Comment by smowden** [comment]
first time i see a .rip/.ri file extension

**Comment by tkon99** [comment]
Well, I don't see why it has to be an .es6 or .es6.js file. It doesn't fit in normal workflow, making it harder to integrate babel into my daily development. I found it to be "RIP", so I figured this would be a kind way of making you aware of it. ;-)

**Comment by jeffshaver** [comment]
I don't understand the benefit of this pull request at all

**Comment by grigio** [comment]
@tkon99 now you can specify the Ecmascript6 extension you prefere per project

**Comment by tkon99** [comment]
Great!

Op wo 1 apr. 2015 14:57 schreef Luigi Maselli notifications@github.com:

**Pull request closed without merging**
